/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pub.techfun.mybatis.easydao;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;
import pub.techfun.mybatis.plugin.common.task.CreateConfigFileTask;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class CarbonDockerPluginPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("pub.techfun.mybatis.plugin.easydao");

        // Verify the result
        assertNotNull(project.getTasks().findByName(CreateConfigFileTask.TASK_NAME));
    }
}
