/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pub.techfun.mybatis.easydao;


import org.gradle.api.Plugin;
import org.gradle.api.Project;
import pub.techfun.mybatis.easydao.task.GenerateFileTask;
import pub.techfun.mybatis.plugin.common.task.CreateConfigFileTask;
import pub.techfun.mybatis.plugin.common.task.CreateConfigFolderTask;
import pub.techfun.mybatis.plugin.common.util.LogUtil;

/**
 * @author henry
 */
public class MybatisPluginEasydao implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
		LogUtil.setPluginName("gradle-mybatis-plugin-easydao");
		project.getTasks().register(CreateConfigFolderTask.TASK_NAME, CreateConfigFolderTask.class);
		project.getTasks().register( CreateConfigFileTask.TASK_NAME, CreateConfigFileTask.class);
		project.getTasks().register(GenerateFileTask.TASK_NAME, GenerateFileTask.class);
    }
}
