/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pub.techfun.docker.plugin.cmd;

import pub.techfun.docker.plugin.cmd.task.CreateDockerFolderTask;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'carbon.docker.plugin.greeting' plugin.
 */
class CarbonDockerPluginPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
		project.getPlugins().apply("java");
        project.getPlugins().apply("carbon.docker.plugin.cmd");

        // Verify the result
        assertNotNull(project.getTasks().findByName(CreateDockerFolderTask.TASK_NAME));
    }
}
