/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pub.techfun.docker.plugin.cmd;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import pub.techfun.docker.plugin.common.task.CreateDockerFolderTask;

import static org.junit.jupiter.api.Assertions.*;

class CarbonDockerPluginPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
		project.getPlugins().apply("java");
        project.getPlugins().apply("pub.techfun.docker.plugin.cmd");

        // Verify the result
        assertNotNull(project.getTasks().findByName(CreateDockerFolderTask.TASK_NAME));
    }
}
